# Changes here will be overwritten by Copier.
_commit: 1.8.4
_src_path: gh:pawamoy/copier-uv
author_email: pierre.marijon-ext@aphp.fr
author_fullname: Pierre Marijon
author_username: natir
copyright_date: '2025'
copyright_holder: GCS SeqOIA
copyright_holder_email: pierre.marijon-ext@aphp.fr
copyright_license: MIT
insiders: false
project_description: A python package to request Seqoia dAta laKE
project_name: sake_request
python_package_command_line_name: sake_request
python_package_distribution_name: sake_request
python_package_import_name: sake_request
repository_name: sake_request
repository_namespace: SeqOIA-IT
repository_provider: github.com

