variables:
  PYTHON_VERSION: "3.12"
  BASE_LAYER: "bookworm-slim"


default:
  image: ghcr.io/astral-sh/uv:python$PYTHON_VERSION-$BASE_LAYER


stages:
  - setup
  - test
  - check
  - deploy


before_script:
  - python --version; pip --version # debugging
  - apt-get update; apt-get install make git -y
  - echo "PYTHON_VERSIONS=3.12" >> build.env


setup:
  stage: setup
  variables:
    UV_CACHE_DIR: .uv-cache
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR
  script:
    - make setup
    - uv cache prune --ci


test:
  stage: test
  dependencies:
    - setup
  script:
    - make test


format:
  stage: check
  dependencies:
    - setup
  script:
    - make format


check_quality:
  stage: check
  dependencies:
    - setup
  script:
    - make check-quality


check_typing:
  stage: check
  dependencies:
    - setup
  script:
    - make check-types


check_api:
  stage: check
  dependencies:
    - setup
  script:
    - make check-api


release:
  stage: deploy
  dependencies:
    - setup
    - format
    - test
    - check_quality
    - check_typing
    - check_api
  script:
    - uv tool run --from build pyproject-build
  artifacts:
    paths:
      - "dist/"
